allP = zeros(1,14);i = 1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by2%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by2%Result.mat',2,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by2.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by2.5%Result.mat',2.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by3%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by3%Result.mat',3,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by3.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by3.5%Result.mat',3.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by4%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by4%Result.mat',4,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by4.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by4.5%Result.mat',4.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by5%Result.mat',5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by5.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by5.5%Result.mat',5.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by6%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by6%Result.mat',6,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by6.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by6.5%Result.mat',6.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by7%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by7%Result.mat',7,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by7.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by7.5%Result.mat',7.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by8%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by8%Result.mat',8,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
[ansss] = FinalPrecision('C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType2by8.5%Result.mat','C:\Work\IPTV\IPTV Recommendation\Result\频道二分类阈值实验结果\Trainingset3000WithDuration[10-3600]ChannelType1by8.5%Result.mat',8.5,'C:\Work\IPTV\IPTV Recommendation\dataset\Trainingset3000WithDuration[10-3600].txt');
allP(i) =allP(i)+ansss;i = i+1;
